### ISSUE TITLE
Crashing push on XCode 14 beta

### ISSUE THREAD

**Issue by hugovanderlei** [QuickBirdEng/XCoordinator#233] opened 2022-08-15 14:18 UTC
Crashing push on NavigationController extension, XCode 14 beta 5, is complaining that the method must be made on main thread. 

![Captura de Tela 2022-08-15 às 11 15 46](https://user-images.githubusercontent.com/184836/184652298-8354d2da-d099-404a-a56c-46c878ace697.png)

**Comment by pauljohanneskraft** [comment] 2022-08-15 14:49
@hugovanderlei can you confirm that trigger is called from the main thread in this case?

**Comment by hugovanderlei** [comment] 2022-08-15 15:33
I tested it in both xcodes, and it always worked on XCode 13, where the method was called on the main thread. However, when I use XCode 14, the method is not called on the main thread, as shown in the images.

![Captura de Tela 2022-08-15 às 12 08 27](https://user-images.githubusercontent.com/184836/184666008-54eb0a92-0ff1-49b7-a63d-5c5b77ca59d3.png)

![Captura de Tela 2022-08-15 às 12 18 30](https://user-images.githubusercontent.com/184836/184665993-39746b37-127a-491f-8655-a5e2a43879e7.png)

**Comment by joaoduartemariucio** [comment] 2022-09-16 13:24
@pauljohanneskraft  Same problem here, any news?

**Comment by canbalkaya** [comment] 2022-09-20 09:39
Same problem. Any news?

**Comment by hugovanderlei** [comment] 2022-09-20 10:26
I was able to resolve it on my project. On XCode 14, I observed that even when an async trigger method is called by another method with @MainActor, the trigger method is no longer on the main thread.

I believe adding @MainActor to the async trigger might work.

<img width="634" alt="Captura de Tela 2022-09-20 às 07 25 08" src="https://user-images.githubusercontent.com/184836/191234289-511d3ce6-70d5-4a78-8886-0f5e4b08c23e.png">



In my project, I had to use MainActor.run to call the trigger.


```  await MainActor.run {
            router.trigger(.checkAuthentication)
        }```

This forces the trigger method to be executed on the main thread.

**Comment by hugovanderlei** [comment] 2022-09-20 10:40
In my case it only happened on async methods

**Comment by canbalkaya** [comment] 2022-10-09 07:47
Any news?

**Comment by manuel-ceschi** [comment] 2023-01-05 10:48
any news?

**Comment by alessiolapenna** [comment] 2023-01-20 05:43
any news?

**Comment by mseverinoPhotosi** [comment] 2023-01-23 08:05
any news?

**Comment by pauljohanneskraft** [comment] 2023-01-23 16:34
Sorry for the long wait. I will try to figure out the root cause to this - can anyone confirm or deny that this only affects the async extensions and not the regular trigger methods?

**Comment by pauljohanneskraft** [comment] 2023-02-02 14:55
I pushed a potential fix to https://github.com/QuickBirdEng/XCoordinator/pull/239 - Can anyone confirm that this solves the issue?

**Comment by manuel-ceschi** [comment] 2023-02-18 11:54
Hi @pauljohanneskraft, I have tried your fix in all the afflicted sections in my app and everything is fixed. Thank you. My team is looking forward to the new version. well done!

**Comment by pauljohanneskraft** [comment] 2023-02-18 11:56
Thank you very much for the feedback - I will try to release it in about a week, hope that's fine. Until then, feel free to specify that branch for now as a temporary workaround.

**Comment by pauljohanneskraft** [comment] 2023-02-28 16:09
The fix has just been merged and will be released shortly.

**Closed by pauljohanneskraft** 2023-02-28 16:09 UTC
